### ISSUE TITLE
Version with Twitter Future

### ISSUE THREAD

**Issue by jdegoes** [zio/interop-twitter#1]
I think we should version this library with Twitter Future.

e.g. if you're using Twitter Future 1.0, then you pull in `interop-twitter` 1.0.

We can use the micro version for backward-compatible updates within a Twitter Future version.

Thoughts?

**Comment by mijicd** [comment]
Makes sense to me. As the matter of fact, this scheme might be applicable to most of the remaining interops.

**Comment by NeQuissimus** [comment]
Made an RC aligned with the Twitter version
