### ISSUE TITLE
Why do we have to pass a `Task[TwitterFuture[_]]` instead of a `=> TwitterFuture[_]`?

### ISSUE THREAD

**Issue by davoclavo** [zio/interop-twitter#117]
I've been using this library to adapt our TwitterFuture code to ZIO and I was just wondering why does the signature of the main conversion function expects the Twitter Future to be passed wrapped in a `Task`

`def fromTwitterFuture[A](future: Task[Future[A]]): Task[A]`

instead of just passing it as call-by-name argument to make the interface simpler and keep it lazy? (and wrap the future in `Task` within the implementation)

`def fromTwitterFuture[A](future: => Future[A]): Task[A]`

I'm able to submit a PR if this is considered a good improvement.

**Comment by mijicd** [comment]
@davoclavo sorry for the late response. Please submit a PR for that!
